apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: friendlyhello
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: friendlyhello
        spec:
            containers:
                - name:  friendlyhello
                  image: adiq94/friendlyhello:latest
                  ports:
                      - containerPort: 80
